# Generated by Django 4.2.25 on 2025-10-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_weeklyorder_cash_received_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts",
                to="orders.weeklyorder",
            ),
        ),
    ]
